import { z } from 'zod';

const countries = [
  {
    name: 'United States of America',
    alpha2: 'US',
    alpha3: 'USA',
    countryCode: '840',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Northern America',
    subRegionCode: '021',
  },
  {
    name: 'United Kingdom',
    alpha2: 'GB',
    alpha3: 'GBR',
    countryCode: '826',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    countryCode: '004',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    countryCode: '248',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    countryCode: '008',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    alpha3: 'DZA',
    countryCode: '012',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    countryCode: '016',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    countryCode: '020',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    countryCode: '024',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    countryCode: '660',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    countryCode: '010',
    region: '',
    regionCode: '',
    subRegion: '',
    subRegionCode: '',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    countryCode: '028',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    countryCode: '032',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    countryCode: '051',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    countryCode: '533',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    countryCode: '036',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    countryCode: '040',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    countryCode: '031',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    countryCode: '044',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    countryCode: '048',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    countryCode: '050',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    countryCode: '052',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    countryCode: '112',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    countryCode: '056',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    countryCode: '084',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    countryCode: '204',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    countryCode: '060',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Northern America',
    subRegionCode: '021',
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    countryCode: '064',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2: 'BO',
    alpha3: 'BOL',
    countryCode: '068',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2: 'BQ',
    alpha3: 'BES',
    countryCode: '535',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    countryCode: '070',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    countryCode: '072',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Bouvet Island',
    alpha2: 'BV',
    alpha3: 'BVT',
    countryCode: '074',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    countryCode: '076',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2: 'IO',
    alpha3: 'IOT',
    countryCode: '086',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Brunei Darussalam',
    alpha2: 'BN',
    alpha3: 'BRN',
    countryCode: '096',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    countryCode: '100',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    countryCode: '854',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    countryCode: '108',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Cabo Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    countryCode: '132',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    countryCode: '116',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    countryCode: '120',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    countryCode: '124',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Northern America',
    subRegionCode: '021',
  },
  {
    name: 'Cayman Islands',
    alpha2: 'KY',
    alpha3: 'CYM',
    countryCode: '136',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    countryCode: '140',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    countryCode: '148',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    countryCode: '152',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha3: 'CHN',
    countryCode: '156',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    countryCode: '162',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    countryCode: '166',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    countryCode: '170',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    countryCode: '174',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Congo',
    alpha2: 'CG',
    alpha3: 'COG',
    countryCode: '178',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Congo, Democratic Republic of the',
    alpha2: 'CD',
    alpha3: 'COD',
    countryCode: '180',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Cook Islands',
    alpha2: 'CK',
    alpha3: 'COK',
    countryCode: '184',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    countryCode: '188',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: "Côte d'Ivoire",
    alpha2: 'CI',
    alpha3: 'CIV',
    countryCode: '384',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    countryCode: '191',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    countryCode: '192',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Curaçao',
    alpha2: 'CW',
    alpha3: 'CUW',
    countryCode: '531',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    countryCode: '196',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Czechia',
    alpha2: 'CZ',
    alpha3: 'CZE',
    countryCode: '203',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    countryCode: '208',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    countryCode: '262',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    countryCode: '212',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    countryCode: '214',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    countryCode: '218',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    countryCode: '818',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    countryCode: '222',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    countryCode: '226',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    countryCode: '232',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    countryCode: '233',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Eswatini',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    countryCode: '748',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    countryCode: '231',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2: 'FK',
    alpha3: 'FLK',
    countryCode: '238',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    countryCode: '234',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    countryCode: '242',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Melanesia',
    subRegionCode: '054',
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    countryCode: '246',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    countryCode: '250',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    alpha3: 'GUF',
    countryCode: '254',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'French Polynesia',
    alpha2: 'PF',
    alpha3: 'PYF',
    countryCode: '258',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'French Southern Territories',
    alpha2: 'TF',
    alpha3: 'ATF',
    countryCode: '260',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha3: 'GAB',
    countryCode: '266',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    countryCode: '270',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    countryCode: '268',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    countryCode: '276',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    countryCode: '288',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    countryCode: '292',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    countryCode: '300',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    alpha3: 'GRL',
    countryCode: '304',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Northern America',
    subRegionCode: '021',
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    countryCode: '308',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    alpha3: 'GLP',
    countryCode: '312',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    alpha3: 'GUM',
    countryCode: '316',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    countryCode: '320',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    alpha3: 'GGY',
    countryCode: '831',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    countryCode: '324',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    countryCode: '624',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    countryCode: '328',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    countryCode: '332',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2: 'HM',
    alpha3: 'HMD',
    countryCode: '334',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'Holy See',
    alpha2: 'VA',
    alpha3: 'VAT',
    countryCode: '336',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    countryCode: '340',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Hong Kong',
    alpha2: 'HK',
    alpha3: 'HKG',
    countryCode: '344',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    countryCode: '348',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    countryCode: '352',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'India',
    alpha2: 'IN',
    alpha3: 'IND',
    countryCode: '356',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    countryCode: '360',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2: 'IR',
    alpha3: 'IRN',
    countryCode: '364',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    countryCode: '368',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    countryCode: '372',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    countryCode: '833',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    countryCode: '376',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    countryCode: '380',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    alpha3: 'JAM',
    countryCode: '388',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    countryCode: '392',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    alpha3: 'JEY',
    countryCode: '832',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    countryCode: '400',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    countryCode: '398',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Central Asia',
    subRegionCode: '143',
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    countryCode: '404',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    countryCode: '296',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2: 'KP',
    alpha3: 'PRK',
    countryCode: '408',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Korea, Republic of',
    alpha2: 'KR',
    alpha3: 'KOR',
    countryCode: '410',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    countryCode: '414',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    alpha3: 'KGZ',
    countryCode: '417',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Central Asia',
    subRegionCode: '143',
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: 'LA',
    alpha3: 'LAO',
    countryCode: '418',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    countryCode: '428',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    alpha3: 'LBN',
    countryCode: '422',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    countryCode: '426',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    countryCode: '430',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    alpha3: 'LBY',
    countryCode: '434',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    countryCode: '438',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    countryCode: '440',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    countryCode: '442',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Macao',
    alpha2: 'MO',
    alpha3: 'MAC',
    countryCode: '446',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    countryCode: '450',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    countryCode: '454',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    alpha3: 'MYS',
    countryCode: '458',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    countryCode: '462',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    countryCode: '466',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    countryCode: '470',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    countryCode: '584',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    countryCode: '474',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    countryCode: '478',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    countryCode: '480',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    alpha3: 'MYT',
    countryCode: '175',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    alpha3: 'MEX',
    countryCode: '484',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2: 'FM',
    alpha3: 'FSM',
    countryCode: '583',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Moldova, Republic of',
    alpha2: 'MD',
    alpha3: 'MDA',
    countryCode: '498',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    countryCode: '492',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    alpha3: 'MNG',
    countryCode: '496',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    countryCode: '499',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    alpha3: 'MSR',
    countryCode: '500',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    countryCode: '504',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    countryCode: '508',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    countryCode: '104',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    countryCode: '516',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    countryCode: '520',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    countryCode: '524',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    countryCode: '528',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    alpha3: 'NCL',
    countryCode: '540',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Melanesia',
    subRegionCode: '054',
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    countryCode: '554',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    countryCode: '558',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    countryCode: '562',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    countryCode: '566',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    countryCode: '570',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    alpha3: 'NFK',
    countryCode: '574',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Australia and New Zealand',
    subRegionCode: '053',
  },
  {
    name: 'North Macedonia',
    alpha2: 'MK',
    alpha3: 'MKD',
    countryCode: '807',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    countryCode: '580',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    countryCode: '578',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    countryCode: '512',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    countryCode: '586',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    countryCode: '585',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Palestine, State of',
    alpha2: 'PS',
    alpha3: 'PSE',
    countryCode: '275',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    alpha3: 'PAN',
    countryCode: '591',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    alpha3: 'PNG',
    countryCode: '598',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Melanesia',
    subRegionCode: '054',
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    countryCode: '600',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    alpha3: 'PER',
    countryCode: '604',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    countryCode: '608',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Pitcairn',
    alpha2: 'PN',
    alpha3: 'PCN',
    countryCode: '612',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    countryCode: '616',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    countryCode: '620',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Puerto Rico',
    alpha2: 'PR',
    alpha3: 'PRI',
    countryCode: '630',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    countryCode: '634',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Réunion',
    alpha2: 'RE',
    alpha3: 'REU',
    countryCode: '638',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    countryCode: '642',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Russian Federation',
    alpha2: 'RU',
    alpha3: 'RUS',
    countryCode: '643',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    countryCode: '646',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    countryCode: '652',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2: 'SH',
    alpha3: 'SHN',
    countryCode: '654',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    alpha3: 'KNA',
    countryCode: '659',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Saint Lucia',
    alpha2: 'LC',
    alpha3: 'LCA',
    countryCode: '662',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Saint Martin (French part)',
    alpha2: 'MF',
    alpha3: 'MAF',
    countryCode: '663',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2: 'PM',
    alpha3: 'SPM',
    countryCode: '666',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Northern America',
    subRegionCode: '021',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2: 'VC',
    alpha3: 'VCT',
    countryCode: '670',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    countryCode: '882',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    countryCode: '674',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Sao Tome and Principe',
    alpha2: 'ST',
    alpha3: 'STP',
    countryCode: '678',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    countryCode: '682',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    countryCode: '686',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    countryCode: '688',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    countryCode: '690',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    countryCode: '694',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    countryCode: '702',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2: 'SX',
    alpha3: 'SXM',
    countryCode: '534',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    countryCode: '703',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    countryCode: '705',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    alpha3: 'SLB',
    countryCode: '090',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Melanesia',
    subRegionCode: '054',
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    alpha3: 'SOM',
    countryCode: '706',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    countryCode: '710',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
    countryCode: '239',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    alpha3: 'SSD',
    countryCode: '728',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    countryCode: '724',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Southern Europe',
    subRegionCode: '039',
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    countryCode: '144',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Southern Asia',
    subRegionCode: '034',
  },
  {
    name: 'Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    countryCode: '729',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    countryCode: '740',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2: 'SJ',
    alpha3: 'SJM',
    countryCode: '744',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    countryCode: '752',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Northern Europe',
    subRegionCode: '154',
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    countryCode: '756',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Western Europe',
    subRegionCode: '155',
  },
  {
    name: 'Syrian Arab Republic',
    alpha2: 'SY',
    alpha3: 'SYR',
    countryCode: '760',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Taiwan, Province of China',
    alpha2: 'TW',
    alpha3: 'TWN',
    countryCode: '158',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Eastern Asia',
    subRegionCode: '030',
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    countryCode: '762',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Central Asia',
    subRegionCode: '143',
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2: 'TZ',
    alpha3: 'TZA',
    countryCode: '834',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    countryCode: '764',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    countryCode: '626',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    alpha3: 'TGO',
    countryCode: '768',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    alpha3: 'TKL',
    countryCode: '772',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    countryCode: '776',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    countryCode: '780',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    countryCode: '788',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    countryCode: '792',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    alpha3: 'TKM',
    countryCode: '795',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Central Asia',
    subRegionCode: '143',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2: 'TC',
    alpha3: 'TCA',
    countryCode: '796',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    alpha3: 'TUV',
    countryCode: '798',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    countryCode: '800',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    countryCode: '804',
    region: 'Europe',
    regionCode: '150',
    subRegion: 'Eastern Europe',
    subRegionCode: '151',
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    countryCode: '784',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2: 'UM',
    alpha3: 'UMI',
    countryCode: '581',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Micronesia',
    subRegionCode: '057',
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    countryCode: '858',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    countryCode: '860',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Central Asia',
    subRegionCode: '143',
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    countryCode: '548',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Melanesia',
    subRegionCode: '054',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2: 'VE',
    alpha3: 'VEN',
    countryCode: '862',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Viet Nam',
    alpha2: 'VN',
    alpha3: 'VNM',
    countryCode: '704',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'South-eastern Asia',
    subRegionCode: '035',
  },
  {
    name: 'Virgin Islands (British)',
    alpha2: 'VG',
    alpha3: 'VGB',
    countryCode: '092',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2: 'VI',
    alpha3: 'VIR',
    countryCode: '850',
    region: 'Americas',
    regionCode: '019',
    subRegion: 'Latin America and the Caribbean',
    subRegionCode: '419',
  },
  {
    name: 'Wallis and Futuna',
    alpha2: 'WF',
    alpha3: 'WLF',
    countryCode: '876',
    region: 'Oceania',
    regionCode: '009',
    subRegion: 'Polynesia',
    subRegionCode: '061',
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha3: 'ESH',
    countryCode: '732',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Northern Africa',
    subRegionCode: '015',
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    countryCode: '887',
    region: 'Asia',
    regionCode: '142',
    subRegion: 'Western Asia',
    subRegionCode: '145',
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    countryCode: '894',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    countryCode: '716',
    region: 'Africa',
    regionCode: '002',
    subRegion: 'Sub-Saharan Africa',
    subRegionCode: '202',
  },
] as const;

export const alpha2CountryCodes = [
  'US',
  'GB',
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'CV',
  'KH',
  'CM',
  'CA',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CW',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'SZ',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HK',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MO',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MK',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SX',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'UM',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VG',
  'VI',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW',
] as const;

export const alpha3CountryCodes = [
  'USA',
  'GBR',
  'AFG',
  'ALA',
  'ALB',
  'DZA',
  'ASM',
  'AND',
  'AGO',
  'AIA',
  'ATA',
  'ATG',
  'ARG',
  'ARM',
  'ABW',
  'AUS',
  'AUT',
  'AZE',
  'BHS',
  'BHR',
  'BGD',
  'BRB',
  'BLR',
  'BEL',
  'BLZ',
  'BEN',
  'BMU',
  'BTN',
  'BOL',
  'BES',
  'BIH',
  'BWA',
  'BVT',
  'BRA',
  'IOT',
  'BRN',
  'BGR',
  'BFA',
  'BDI',
  'CPV',
  'KHM',
  'CMR',
  'CAN',
  'CYM',
  'CAF',
  'TCD',
  'CHL',
  'CHN',
  'CXR',
  'CCK',
  'COL',
  'COM',
  'COG',
  'COD',
  'COK',
  'CRI',
  'CIV',
  'HRV',
  'CUB',
  'CUW',
  'CYP',
  'CZE',
  'DNK',
  'DJI',
  'DMA',
  'DOM',
  'ECU',
  'EGY',
  'SLV',
  'GNQ',
  'ERI',
  'EST',
  'SWZ',
  'ETH',
  'FLK',
  'FRO',
  'FJI',
  'FIN',
  'FRA',
  'GUF',
  'PYF',
  'ATF',
  'GAB',
  'GMB',
  'GEO',
  'DEU',
  'GHA',
  'GIB',
  'GRC',
  'GRL',
  'GRD',
  'GLP',
  'GUM',
  'GTM',
  'GGY',
  'GIN',
  'GNB',
  'GUY',
  'HTI',
  'HMD',
  'VAT',
  'HND',
  'HKG',
  'HUN',
  'ISL',
  'IND',
  'IDN',
  'IRN',
  'IRQ',
  'IRL',
  'IMN',
  'ISR',
  'ITA',
  'JAM',
  'JPN',
  'JEY',
  'JOR',
  'KAZ',
  'KEN',
  'KIR',
  'PRK',
  'KOR',
  'KWT',
  'KGZ',
  'LAO',
  'LVA',
  'LBN',
  'LSO',
  'LBR',
  'LBY',
  'LIE',
  'LTU',
  'LUX',
  'MAC',
  'MDG',
  'MWI',
  'MYS',
  'MDV',
  'MLI',
  'MLT',
  'MHL',
  'MTQ',
  'MRT',
  'MUS',
  'MYT',
  'MEX',
  'FSM',
  'MDA',
  'MCO',
  'MNG',
  'MNE',
  'MSR',
  'MAR',
  'MOZ',
  'MMR',
  'NAM',
  'NRU',
  'NPL',
  'NLD',
  'NCL',
  'NZL',
  'NIC',
  'NER',
  'NGA',
  'NIU',
  'NFK',
  'MKD',
  'MNP',
  'NOR',
  'OMN',
  'PAK',
  'PLW',
  'PSE',
  'PAN',
  'PNG',
  'PRY',
  'PER',
  'PHL',
  'PCN',
  'POL',
  'PRT',
  'PRI',
  'QAT',
  'REU',
  'ROU',
  'RUS',
  'RWA',
  'BLM',
  'SHN',
  'KNA',
  'LCA',
  'MAF',
  'SPM',
  'VCT',
  'WSM',
  'SMR',
  'STP',
  'SAU',
  'SEN',
  'SRB',
  'SYC',
  'SLE',
  'SGP',
  'SXM',
  'SVK',
  'SVN',
  'SLB',
  'SOM',
  'ZAF',
  'SGS',
  'SSD',
  'ESP',
  'LKA',
  'SDN',
  'SUR',
  'SJM',
  'SWE',
  'CHE',
  'SYR',
  'TWN',
  'TJK',
  'TZA',
  'THA',
  'TLS',
  'TGO',
  'TKL',
  'TON',
  'TTO',
  'TUN',
  'TUR',
  'TKM',
  'TCA',
  'TUV',
  'UGA',
  'UKR',
  'ARE',
  'UMI',
  'URY',
  'UZB',
  'VUT',
  'VEN',
  'VNM',
  'VGB',
  'VIR',
  'WLF',
  'ESH',
  'YEM',
  'ZMB',
  'ZWE',
] as const;

export const alpha2CountryCodeSchema = z.enum(alpha2CountryCodes, {
  invalid_type_error: 'Please use a valid 2 character country code',
});

export const alpha3CountryCodeSchema = z.enum(alpha3CountryCodes, {
  invalid_type_error: 'Please use a valid 3 character country code',
});

export default countries;

export type Country = (typeof countries)[number];

export type CountryAlpha2 = z.infer<typeof alpha2CountryCodeSchema>;

export type CountryAlpha3 = z.infer<typeof alpha3CountryCodeSchema>;

export type CountryCode = Country['countryCode'];

export type CountryRegionCode = Country['regionCode'];


